### ISSUE TITLE
Swift Compiler Error (Xcode): No such module 'NearbyCoreAdapter'

### ISSUE THREAD

**Issue by ynishimi** [IgVelasco/nearby_cross#53]
Hello,
When I tried to run the example on iPhone simulater following [this](https://github.com/IgVelasco/nearby_cross?tab=readme-ov-file#getting-started), I got this error:

```
nishimi@MacBookAir example % flutter run
...
Launching lib/main.dart on iPhone SE (3rd generation) in debug mode...
Warning: Missing build name (CFBundleShortVersionString).
Warning: Missing build number (CFBundleVersion).
Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting
to the App Store.
Running Xcode build...                                                  
Xcode build done.                                           13.8s
Failed to build iOS app
Swift Compiler Error (Xcode): No such module 'NearbyCoreAdapter'
/Users/nishimi/.pub-cache/hosted/pub.dev/nearby_cross-1.0.0/ios/Classes/nearby_dependencies/Advertiser.swift:1
5:7


Package Loading (Xcode): Missing package product 'FlutterGeneratedPluginSwiftPackage'
/Users/nishimi/Dev/flutter/nearby_cross/example/ios/Runner.xcodeproj


Could not build the application for the simulator.
Error launching application on iPhone SE (3rd generation).
```

And the package dependencies page looks like this:
<img width="1439" alt="スクリーンショット 2024-08-14 0 20 07" src="https://github.com/user-attachments/assets/ed9a4916-0e56-409c-909c-7ac82af6ae44">

It seems that `NearbyCoreAdapter` is missing, but I have no idea how to add it to the project.
I would appreciate it if you could help me!

**Comment by IgVelasco** [comment]
@ynishimi let me know if those steps worked for you and I'll  update the documentation

**Comment by ynishimi** [comment]
Thank you for your quick response!
I followed your suggestion and the `NearbyCoreAdapter` seems to have been added.

But an another error remains to occur when building:
```
No such file or directory: '/Users/nishimi/Library/Developer/Xcode/DerivedData/Runner-gkutmtfqvudnyiftlhxssqlsfyqw/Build/Products/Debug-iphonesimulator/PackageFrameworks/NearbyConnectionsDynamic.framework/NearbyConnectionsDynamic'
```

`NearbyConnectionsDynamic` does not exist in the directory, so maybe there is a problem in the framework.

```
nishimi@MacBook-Air NearbyConnectionsDynamic.framework % tree -a
.
├── Info.plist
└── _CodeSignature
    ├── CodeDirectory
    ├── CodeRequirements
    ├── CodeRequirements-1
    ├── CodeResources
    └── CodeSignature

2 directories, 6 files
```

**Comment by IgVelasco** [comment]
Try adding it also in this screen:

**Comment by ynishimi** [comment]
Thank you for your advice!
I did remove and add both `NearbyConnections` and `NearbyConnectionsDynamic`, but unfortunately it didn't work out for me.
I would like to tackle the problem for a bit.

Thank you again for your time!

**Comment by IgVelasco** [comment]
Yeah for now is only physical devices, and weird I got it running with `a5efe8b`  will check a bit when I have more time and improve the doc.

In the following issue of nearby we talked a bit about the difficulty of this imports:

https://github.com/google/nearby/issues/10

Anyways let me know if you have any other problems! @ynishimi
